---
title: "eds_day3_b"
author: "Jared Petry"
date: "2022-08-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

### Make Some Vectors
```{r}
marmots <- c("blue", "green", 4, "yellow")
#----class of object was stored as characters... can't have one vector with different classes within
#----how to check class: 
class(marmots)
```

```{r}
pika <- c(12.4, 5.6, 7.8, 4.9, 6.9)
class(pika)

#---- Scalar multiplier 
scalar_pika <- 5.2*pika
scalar_pika
```

```{r}
bananas <- c(1, 2, 3)
#----add some spaces to make things easier to look at
apples <- c(6, 7, 8)

#----adding and subtracting vectors
bananas + apples 
bananas-apples

#----dot product
bananas %*% apples 
```

### Matrices 
```{r}
my_values <- seq(from= 1, to=10)
#----if you don't include the "by" argument then it will default to counting by 1
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)
#---- just told R to make a matrix out of the sequence with 2 rows and 5 columns 
my_matrix

5* my_matrix
class(my_matrix)
```

```{r}
glimpse(penguins)
```



a cool update 
